version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - backup-storage:/app/storage
      - backup-logs:/app/logs
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_USER=${DB_USER:-backup_manager}
      - POSTGRES_DB=${DB_NAME:-backup_manager}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data:
  backup-storage:
  backup-logs:
